### ISSUE TITLE
"New Question" button in Say Hello! category

### ISSUE THREAD

**Issue by salty-sweet** [CodeMyst/BrackeysForumIssueTracker#21] opened 2020-05-23 05:54 UTC
It is currently looking like the default button which is understandable, but a category for user introductions doesn't seem to be a place for questions.

![image](https://user-images.githubusercontent.com/36786920/82722841-c6d8a580-9cfc-11ea-8c6f-e30277738289.png)

**Comment by Duxez** [comment] 2020-05-23 07:28
Yep we know and will be working on it. Tho it does seem you have some styling problems in that screenshot

**Comment by salty-sweet** [comment] 2020-05-23 07:50
> Tho it does seem you have some styling problems in that screenshot

This was from forums itself :kekw:

**Comment by Duxez** [comment] 2020-05-23 07:54
clear your cache

**Comment by Duxez** [comment] 2020-05-23 09:43
Duplicate of #17

**Closed as completed by Duxez** 2020-05-23 09:43 UTC
Labels: enhancement
